### ISSUE TITLE
反馈个问题，录入key后执行报错

### ISSUE THREAD

**Issue by hanxmvn93992** [liyaodong/appleDnsOptimizer#1]
/root/appleDnsOptimizer/index.js:45
          `Complete task ${dnsQueryTask.data.id}, result count=${taskResult.list?.length}`
                                                                                 ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

独立key，统一 key均尝试报错，对应版本如下
node v12.22.5
npm 7.5.2
yarn 1.22.19

**Comment by nothingrealhappen** [comment]
你 nodejs 版本是多少？感觉是版本太低了
